### ISSUE TITLE
Issue with the parser argument

### ISSUE THREAD

**Issue by fcsonline** [sheerun/prettier-standard#102]
Hi @sheerun,

I'm trying to run `prettier-standard` in some typescript files, running this command:

```bash
prettier-standard "src/**/*.{ts,tsx}" --parser typescript
```

But I get `Cannot provide patterns when --stdin is used`

Checking this line https://github.com/sheerun/prettier-standard/blob/master/src/cli.js#L65
and commenting out the parser check it runs as expected.

Which is the relation between `hasStdin` and `parser` flag?

Thanks!

**Comment by sheerun** [comment]
--parser is meant to be used if providing code via stdin

normally parser is figured out automatically from extension, so in your case `prettier-standard "src/**/*.{ts,tsx}"` should be enough

**Comment by fcsonline** [comment]
Ok. Thanks! 

I was running the command without stdin and the `parser` arguments + the warning message was not clear enough about what was going on.

Closing the issue.

**Comment by sheerun** [comment]
Yes I guess it needs to be improved, thanks :)
