### ISSUE TITLE
How to check for non-style problems?

### ISSUE THREAD

**Issue by DylanVann** [sheerun/prettier-standard#11]
Running standard will tell you if there are things like unused variables.
Running prettier-standard won't.

Ideally I think we want a tool that can automatically format code and also:

- Check that code matches the output format.
- Check that the code follows eslint rules like no unused variables.
- These should be easy for a user to add to CI.

**Comment by DylanVann** [comment]
Maybe using `throws` in `prettierESLintOptions`.

https://github.com/prettier/prettier-eslint#throws

**Comment by sheerun** [comment]
well, the whole point of formatter is to format, not lint, so you don't need to fix anything manually

If you'd like to implement extra flag to also show linting issues, I'm open to it. I don't intent to implement it by myself for the lack of time
