### ISSUE TITLE
Error: You must provide patterns to match outside of git repository

### ISSUE THREAD

**Issue by h-nazzal** [sheerun/prettier-standard#120]
I created this issue because there was no reference on the internet for this error (googling it returned no results at all).Additionally the documentation does not specifically instruct the user to install git.

long story short:
**If you see this error install git. and run**  `git init`

**Comment by olastor** [comment]
What is the rationale behind git being required in order to run this tool?

**Comment by sheerun** [comment]
@olastor It auto-formats files by default. It would not be safe to format files that are not in git in case any bugs are present. Think about it as backup-required rationale
