### ISSUE TITLE
Doesn't show all `standard` errors

### ISSUE THREAD

**Issue by josephfrazier** [sheerun/prettier-standard#14]
First off, thanks for building this! It's a very easy way to have the linting of standard with the formatting of prettier :)

However, prettier-standard doesn't show the same errors that standard does. For example, in the prettier-standard repo at commit 54948a5 (with `prettier-standard` linked globally):

```bash
$ prettier-standard src/format-files.js
1 file was unchanged
$ standard src/format-files.js
standard: Use JavaScript Standard Style (https://standardjs.com)
  /Users/josephfrazier/workspace/prettier-standard/src/format-files.js:39:10: 'coercePath' is defined but never used.
$
```

**Comment by sheerun** [comment]
Prettier-standard is a formatter, not linter. It shouldn't show any errors,
just format :)

**Comment by josephfrazier** [comment]
Ah, I misunderstood. From the name, I had assumed that it would also lint.
