### ISSUE TITLE
Cryptic error when running in NodeJS

### ISSUE THREAD

**Issue by mhkeller** [sheerun/prettier-standard#16]
When I try to import this from a NodeJS script, I get [this error](https://github.com/sheerun/prettier-standard/blob/master/src/no-main.js#L3-L6) saying I should install `prettier-standard` instead. But isn't this `prettier-standard`?

**Comment by sheerun** [comment]
prettier-standard doesn't expose programmatic API. you need to use the cli

**Comment by mhkeller** [comment]
The error message should remove [line 6](https://github.com/sheerun/prettier-standard/blob/master/src/no-main.js#L6) since that is suggesting a solution that is not a solution.

**Comment by sheerun** [comment]
Now I get it :) Thanks for pointing it out, I've removed that line, it should be released soon
