### ISSUE TITLE
Generator function not being fixed

### ISSUE THREAD

**Issue by mcchrish** [sheerun/prettier-standard#19]
Reproduction: https://github.com/mcchrish/prettier-standard-bug.

1. `npm run lint`
2. `npm run format`
3. `npm run lint`

Results to:
```
$ standard index.js
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/mcchris/steve/prettier-standard-bug/index.js:1:9: Missing space before *.
error Command failed with exit code 1.
```

`prettier-standard` will format the following from:
```js
function * test () {
  console.log('test')
}

test()
```
to:
```js
function* test () {
  console.log('test')
}

test()
```

Workaround is running `standard --fix` after running `format`. I assumed this library will just pipe the result of prettier into standard `--fix`. There seems to be a bug?

**Comment by sheerun** [comment]
Indeed, this seems like a bug. I've fixed in in prettier-standard 6.x.x, as not all fixable rules from standard are included by default.
