### ISSUE TITLE
Why not pull from config standard, standard jsx and the plugins?

### ISSUE THREAD

**Issue by charlike** [sheerun/prettier-standard#22]
Hi! I very curious. Neither of the current tools feels and does it in correct way, in my opinion ;/ :laughing: :100:

**Comment by sheerun** [comment]
I'm not sure what you mean, prettier-standard is based on standard's eslint rules

**Comment by tunnckoCore** [comment]
Yea, i see that, but isn't it better to be based directly from the config? Meaning to add it as dependency, so it will take future updates without thinking.

**Comment by sheerun** [comment]
It's OK but we need to filter config by only fixable rules.
Prettier-standard is a fixer, not linter. If you'd like to send an
implementation, please :)
