### ISSUE TITLE
generator function spacing discrepancy between standard --fix and prettier-standard

### ISSUE THREAD

**Issue by bentatum** [sheerun/prettier-standard#25]
Hey there, noticing a discrepancy between the results I get from `prettier-standard` (5.1.0) and `standard --fix` (10.0.3)

`prettier-standard` doesn't like the top line and will reformat to the bottom:
```
export default function * () {}
export default function*() {}
```

and `standard --fix` does the exact opposite 😢

**Comment by sheerun** [comment]
Please try 6.0.0 and check your .eslintrc:

```
$ prettier-standard --version
6.0.0
$ echo 'export default function * () {}' | prettier-standard
export default function * () {}
```
