### ISSUE TITLE
Deprecation warning appears when formatting through stdin

### ISSUE THREAD

**Issue by gerardabello** [sheerun/prettier-standard#27]
Using the example in the Readme this is the output I get:
```bash
$ echo "const {foo} = "bar";" | prettier-standard
The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelfClosing" option instead.
const { foo } = bar
```

**Comment by sheerun** [comment]
I cannot reproduce. What are your eslint, prettier, and prettier-standard versions?

Also, we don't use `react/jsx-space-before-closing` rule..

**Comment by sheerun** [comment]
It's probably your .eslintrc, not prettier-standard

**Comment by gerardabello** [comment]
I think you are right that this rule comes from the `.eslintrc` file in the project, but I think it is not good behavior to include this warnings in the formatted output.

**Comment by sheerun** [comment]
That's right, thanks for pointing it out :)

**Comment by sheerun** [comment]
I tried but I cannot reproduce

**Comment by gerardabello** [comment]
I don't know why but this is not happening anymore.
