### ISSUE TITLE
semi-colons are not removed when import('./file') is used

### ISSUE THREAD

**Issue by faceyspacey** [sheerun/prettier-standard#3]
It appears the new `import().next` syntax breaks prettier-standard--at least when using it without an `.eslintrc.js` file.

**Comment by sheerun** [comment]
What eslint or prettier configuration can fix it?

**Comment by sheerun** [comment]
Hmm, it seems semicolons won't be removed if eslint encounters syntax error while parsing..

**Comment by sheerun** [comment]
@faceyspacey This needs to be fixed in here: https://github.com/prettier/prettier-eslint/issues

Could you raise this issue there?

**Comment by flybayer** [comment]
I think I'm having a similar issue. 

Semicolons are not removed when I have ES6 classes with `something = something else` syntax like
```js
  state = {
    ...
  }

  startRecording = (data) => {
    ...
  }
```

I tried using `babel/semi` as suggested in prettier/prettier-eslint#32 and prettier/prettier-eslint#56 but that's not working.

I have 
```json
  "eslintConfig": {
    "plugins": [
      "babel"
    ],
    "rules": {
      "babel/semi": [
        "error",
        "never"
      ]
    }
  },
```

**Comment by sheerun** [comment]
@flybayer Could you raise this issue to https://github.com/prettier/prettier-eslint/issues ?

**Comment by justsee** [comment]
@flybayer thanks for the head's up on the relevant tickets.

https://github.com/babel/eslint-plugin-babel/pull/121 was merged and the test case supplied outlines an [`.eslintrc`](https://github.com/kentcdodds/eslint-fix-public-class-fields-semi/blob/6628a70d5e9608978b9c9a4457554b9b2bd9b4cf/.eslintrc) that works correctly.

Once that's in place and `eslint-plugin-babel` is installed files should be processed correctly.

**Comment by flybayer** [comment]
@justsee thank you for the .eslintrc link!

I got it working! 

On top of `prettier-standard`, you must install `babel-eslint` and `eslint-plugin-babel`.

Then add this to `package.json`:
```json
  "eslintConfig": {
    "parser": "babel-eslint",
    "plugins": [
      "babel"
    ],
    "rules": {
      "babel/semi": [
        2,
        "never"
      ]
    }
  }

```

**Comment by danawoodman** [comment]
This is unfortunate as now it means you can use prettier-standard out of the gate with any project without configuration. Will this no longer be relevant when `prettier-eslint` fixes things or is this always going to be the case?

**Comment by sheerun** [comment]
I'll try to keep this module useful without configuration. Going to update
in upcoming days

**Comment by sheerun** [comment]
This issue on prettier-eslint needs to be fixed first, please help to make it so:

https://github.com/prettier/prettier-eslint/issues/68

**Comment by sheerun** [comment]
@faceyspacey This should be fixed in 4.1.0, could you check?

**Comment by sheerun** [comment]
Also, please feel free to add yourself to contributors list

**Comment by danawoodman** [comment]
@sheerun nice, this seems to do it! Thanks! 🍻
