### ISSUE TITLE
[suggestion] Configure GreenKeeper or similar to keep dependencies updated

### ISSUE THREAD

**Issue by stefanmaric** [sheerun/prettier-standard#32]
First of all, thanks for this project! :heart: 

So currently `prettier-standard` is using [an exact version of  `prettier`](https://github.com/sheerun/prettier-standard/blob/master/package.json#L32) instead of a range, `1.7.0` specifically. Version `1.7.4` is out already and `prettier-standard` does not benefit from those patches.

Cannot tell if there's a reason behind using the exact version instead of the caret (`^`) range. I would use the range instead.

Additionally, I would set up a service like greenkeeper.io to help with maintenance.

Love,

**Comment by sheerun** [comment]
The reason is so formatting (i.e. prettier version) is not updated when prettier-standard is installed at different point in time. But I guess you're right, I could relax it for patch releases.

**Comment by sheerun** [comment]
I've relaxed prettier version in 7.0.2, and will try to integrate with greenkeeper. Feel free to add yourself to conrtibutors in the readme :)
