### ISSUE TITLE
Conflicts when using standard babel-eslint parser.

### ISSUE THREAD

**Issue by LightningK0ala** [sheerun/prettier-standard#39]
I'm using decorators in my project so to get standard working I have this in my package.json:
``` 
"standard": {
  "parser": "babel-eslint"
}
```
When prettier-standard is also installed, I get errors like `'observer' is defined but never used`.

Prettier-standard is somehow breaking the lint detection that my imports are in fact being used as decorators. Could there be a conflict in one of the dependencies? Any suggestions on a fix?

**Comment by sheerun** [comment]
maybe you need to use eslint 4.0 and presets for it, because that's what prettier-eslint uses (and prettier-standard uses prettier-eslint).

**Comment by whphhg** [comment]
@jcsmesquita Looks like you ran into the same bug as me (#30). If you have a moment, can you please try saving any file that uses decorators to see if the saved file will start being returned by `standard` for decorator issue?

**Comment by sheerun** [comment]
This should be fixed in prettier-standard@9
