### ISSUE TITLE
Wrong 'brace-style' (non-standard)

### ISSUE THREAD

**Issue by mesqueeb** [sheerun/prettier-standard#43]
I have a problem with the following:
```
if (!id) { return }
```
get's fixed to:
```
if (!id) {
  return
}
```
However, I don't think this rule is written anywhere in the standard ruleset. And I'd like prettier-standard to not touch these lines...

Any idea how to fix this?

**Comment by sheerun** [comment]
this is what prettier enforces. if you don't like prettier rules, you can just use `standard --fix`

**Comment by sheerun** [comment]
or make a PR to prettier that fixes this behavior

**Comment by mesqueeb** [comment]
@sheerun Oh I see! I thought that only the rules of Standard were applied, but the instant formatting functionality of Prettier.

Does Prettier have a ruleset itself which also gets applied, other from the max. 90 char line length?

Best regards.

**Comment by mesqueeb** [comment]
@sheerun 
After more research I found out that:

The [brace-style of standard](https://github.com/standard/standard/blob/master/docs/RULES-en.md#javascript-standard-style) is **1tbs**.
Together with `"allowSingleLine": true`.

However, the brace-style prettier-standard uses is **stroustrup**.
Together with `"allowSingleLine": false`.

See here [ESlint](https://eslint.org/docs/rules/brace-style) for more details on these differences.

Can you please change the repository to **1tbs**.
Together with `"allowSingleLine": true`?

**Comment by mesqueeb** [comment]
Dear @sheerun 
I took a look further into this repository.
It seems like you correctly import the standard-ruleset from here:
https://github.com/sheerun/eslint-config-standard/blob/master/eslintrc.json

This in turn **does have** the correct brace-style.

So I think there is something else that's messing with the brace-style option inside your app, I'm not sure where yet.

**Comment by mesqueeb** [comment]
@sheerun 
Any ideas what could be changing the brace-style behaviour of `"brace-style": ["error", "1tbs", { "allowSingleLine": true }],`?

Because you **correctly** pull the settings from [eslintrc](https://github.com/sheerun/eslint-config-standard/blob/master/eslintrc.json), yet prettier-standard is using `{ "allowSingleLine": false }`...

**Comment by rafaelrinaldi** [comment]
This tool seems to be ignoring the `.eslintrc` file. Overriding rules doesn't work.

**Comment by sheerun** [comment]
prettier-standard 9.0.0 now directly uses prettierx for formatting, so if you'd like to customize formatting you need to contribute there: https://github.com/brodybits/prettierx 

then you'll be able to customize formatting in your repository by creating custom .prettierrc file
