### ISSUE TITLE
Ignoring files

### ISSUE THREAD

**Issue by Kikobeats** [sheerun/prettier-standard#50]
Hello,

Could be possible that prettier-standard ignore files based on standard `ignore` property?

```
"standard": {
    "globals": [
      "fetch"
    ],
    "parser": "babel-eslint",
    "ignore": [ ←yep
      "/lib/"
    ]
  }
```

**Comment by rafaelrinaldi** [comment]
I've been trying to achieve the same result via [`.prettierignore`](https://prettier.io/docs/en/ignore.html) without success. It seems `prettier-standard` ignores this feature.

**Comment by sheerun** [comment]
my guess is that for now you need to ignore files in both places

**Comment by rafaelrinaldi** [comment]
Just for the record I've also tried to pass down ignore patterns using globs to `prettier-standard`. Like:

```sh
prettier-standard '.json' '!package.json'
```
<sup>Should format everything but `package.json` in this case</sup>

It doesn't work with this library but it does work with `prettier`.

**Comment by rossvz** [comment]
Any update on this? I'm working in a project that requires standardJS code style, but I'd love to have prettier formatting. The only trick is we have one library file that's a few thousands lines long that was imported from legacy code and should NOT be formatted. It seems we can't get this package to respect the `.prettierignore`

**Comment by sheerun** [comment]
I'm open for PR that fixes it

**Comment by millette** [comment]
I copied the content of my .gitignore to .eslintignore:

```
node_modules/
public
.gatsby-context.js
.DS_Store
.intermediate-representation/
.cache/
.vscode/
```

That works. The original standard linter uses the .gitignore file by default. That would be handy here too.

**Comment by sheerun** [comment]
prettier-standard 9.0.0 uses now just prettierx for formatting so you can use `.prettierignore` and any other ignoring method available to prettier

**Comment by miguelmota** [comment]
Yep `.prettierignore` works great

**Comment by wormple12** [comment]
Is it possible to add support for prettier's CLI options, for this use case specifically "--ignore-path"? I'm using this package to simplify things, and files like .prettierignore crowds my root folder, so it would be nice to be able to simply link prettier-standard to my .gitignore file.
