### ISSUE TITLE
Explain why both are needed

### ISSUE THREAD

**Issue by jedahan** [sheerun/prettier-standard#53]
It would be great, for someone newer to all the tools available, what the benefits of using both standard and prettier are.

From what I understand, its that standard is used to enforce code quality rules, like no unused vars, whereas prettier is just about formatting style. If that's correct, it would be useful to put that somewhere in the readme.

**Comment by sheerun** [comment]
prettier-standard is analogue of just prettier with standard rules, but if you want to add something to the readme I'm open for PR

**Comment by jedahan** [comment]
Ahh that explanation helps a lot and its kinda hard for me to think of what sentence would have clarified whats already there
