### ISSUE TITLE
prettier-standard indentation

### ISSUE THREAD

**Issue by thelinuxlich** [sheerun/prettier-standard#56]
I had to disable prettier-standard because it is indenting files in a way standard doesn't like, I'm getting  errors like: "Standard: expected indentation of 18 spaces but found 20. (indent)"

**Comment by sheerun** [comment]
prettier-standard 9.0.0 now uses just prettierx for formatting. it means you need to use https://github.com/prettier/eslint-config-prettier in your .eslintrc if you want to additinally lint your code with eslint
