### ISSUE TITLE
Issue with rule standard/computed-property-even-spacing

### ISSUE THREAD

**Issue by jyboudreau** [sheerun/prettier-standard#57]
When linting with standard, prettier-standard formatting conflicts with the rule standard/computed-property-even-spacing.

Similar to https://github.com/prettier/eslint-config-prettier/issues/29

Prettier standard wants this:
```
const { whatever } = loooooooooooooooooooooooong[
      something
].some.thiiiiiiiiiiiiing[0]
```

While standard wants:
```
const { whatever } = loooooooooooooooooooooooong[something].some.thiiiiiiiiiiiiing[0]
```

**Comment by jyboudreau** [comment]
👍 That does work. Thanks for the workaround, however I would still consider this a bug with prettier-standard.

Since prettier-standard is a formatter and not a linter, it seems that it should be compatible with the standard linter ruleset as is without disabling inconvenient rules. After all, it's a replacement for prettier, not standard.

I understand however that it's not necessarily easy to marry the two since standard also likes to be a formatter 😉

**Comment by sheerun** [comment]
This is not a workaround, but a solution. Eslint isn't able to fix this whitespace automatically.

**Comment by sheerun** [comment]
you can

**Comment by sheerun** [comment]
prettier-standard 9.0.0 now uses just prettierx for formatting and we recommend using https://github.com/prettier/eslint-config-prettier in .eslintrc to disable any non-compatible whitespace rules set by standard. unfortunately it's not possible to have true 1:1 match between prettier and standard, but we're pretty close :) you can contribute or raise issues to https://github.com/brodybits/prettierx to fix remaining incompatibilities

**Comment by havenchyk** [comment]
> unfortunately it's not possible to have true 1:1 match between prettier and standard

@sheerun does it mean that some of rules should be disabled to prevent conflicts with `eslint-config-standard` and `eslint-confit-standard-jsx`

I see `indent` and `react/jsx-curly-newline` have conflicts at the moment, so can I just disable them and rely on `prettier-standard` instead?
