### ISSUE TITLE
[Vue] Standardjs rule `space-before-function-paren` not respected

### ISSUE THREAD

**Issue by nolde** [sheerun/prettier-standard#58]
[Standardjs](https://standardjs.com/) determines that "_space after function name function name (arg) { ... }_" as a rule.

When running that in a Vue file, with `vue-plugin-eslint` enabled, and `space-before-function-paren` set to `always`. it still removes spaces before the parens inside vue single file components.

**Comment by sheerun** [comment]
prettier-standard 9.0.0 uses just prettierx for formatting so if you'd like to fix this issue you need to contribute to it: https://github.com/brodybits/prettierx

**Comment by sheerun** [comment]
(or raise this issue there)
