### ISSUE TITLE
--dry-run?

### ISSUE THREAD

**Issue by rjhilgefort** [sheerun/prettier-standard#59]
Is there a way to run this as a linter and not have it `--write` and/or `--fix`? My use case is that I want to have the linter run as an `onchange` event and I don't want it writing files and causing my editor to prompt me that the buffer has changed. Thanks!

**Comment by thejohnfreeman** [comment]
Is this a duplicate of #17?

**Comment by rjhilgefort** [comment]
@thejohnfreeman Yep! Didn't see that issue. I'll close this and start following #17. Thanks for linking the issues.
