### ISSUE TITLE
Standard 12

### ISSUE THREAD

**Issue by timdp** [sheerun/prettier-standard#63]
Now that standard@12 is out, it'd be awesome if this package could be updated to use that.

I've been locking down my version of standard to 10 because using version 11 broke stuff. I'm guessing version 12 isn't going to be any better.

Is there a formal to-do list for upgrading? I assume it involves upgrading eslint-config-standard as well as eslint itself?

Thanks!

**Comment by lannonbr** [comment]
The issue with Standard 11 was a deep dependency issue was arising when ESLint 4.x and 5.x were both installed. As long as all of the packages which depend on ESLint are up to 5.x, it should be fine

**Comment by wmhilton** [comment]
But `prettier-standard` has a direct dependency on eslint 4.x which is why it's breaking I think.

**Comment by timdp** [comment]
That, and I was able to create a situation where prettier-standard produced code that passed Standard v10 and failed v11. Unfortunately, I didn't save it.

**Comment by sheerun** [comment]
You can send PR to prettier-eslint that adds support for eslint 5:
https://github.com/prettier/prettier-eslint/issues/193

**Comment by sheerun** [comment]
prettier-standard 9.0.0 no longer uses eslint --fix (or standard --fix) for formatting so it is not relevant now
