### ISSUE TITLE
JSX Fragments cause formatting errors

### ISSUE THREAD

**Issue by ggascoigne** [sheerun/prettier-standard#66]
Prettier-standard generates incorrect code when it sees an abbreviated react fragment.

```jsx
    <>
        <div>
            ... some content
        </div>
    </>
```

gets formatted as

```jsx
    <>'        '<div>
            ... some content
        </div>'    '</>
```

causing whitespace and quotes to be injected into the result.

Switching to <React.Fragment> generates the correct result and is a viable work-around.

It would be nice if the abbreviated syntax worked correctly.

Tested using prettier-standard 8.0.1

There's a somewhat related bug on prettier which was fixed a while ago.

https://github.com/prettier/prettier/issues/3341

**Comment by rafaelrinaldi** [comment]
I'm running into the same issue.

**Comment by sheerun** [comment]
prettier-standard 9.0.0 uses newest version of prettier so it should fix this problem
