### ISSUE TITLE
Vim integration mangles code

### ISSUE THREAD

**Issue by danawoodman** [sheerun/prettier-standard#7]
From what I can tell, the vim integration does some bizarre things to the buffer code. 

I've added `autocmd BufWritePre *.js :normal gggqG` to my `.vimrc` and when I save my files, all the contents get turned into one long line of code. Here is a video of it happening:

![](https://cl.ly/k1WN/Screen%20Recording%202017-04-16%20at%2006.21%20PM.gif)

This might be a .vimrc conflict but I'm not sure how to determine what is at fault. If I run `:!prettier-standard %` in the buffer the file gets modified by prettier-standard correctly.

Thanks for any suggestions

**Comment by danawoodman** [comment]
It appears if I use Neoformat with the follow I can get the result I want:

```vim
autocmd BufWritePre *.js Neoformat
autocmd FileType javascript set formatprg=prettier-standard
let g:neoformat_try_formatprg = 1
```

**Comment by sheerun** [comment]
The command I use is `:%!prettier-standard`, and I don't experience any joining of lines ;/

If this still happens, I suggest raising this issue to https://github.com/prettier/prettier as we use the same API and same suggestion of integrating with Vim

**Comment by danawoodman** [comment]
@sheerun you mean you're running that command manually or that is what you're passing into `formatprg`?

**Comment by sheerun** [comment]
manually

**Comment by sheerun** [comment]
Are you on windows?

**Comment by danawoodman** [comment]
@sheerun I'm talking about the `autocmd` which runs automatically, not running manually
