### ISSUE TITLE
Flow generics are not handled correctly

### ISSUE THREAD

**Issue by KidkArolis** [sheerun/prettier-standard#70]
I don't know if this is an issue with `prettier` or `prettier-standard`, but this how this code gets formatted into invalid syntax:

```diff
import { withRouter } from 'next/router'
import type { Router } from 'next/router'

type Props = {
  router: Router
}

-const MyComponent = withRouter<Props>(({ router }: Props) => ())
+const MyComponent = withRouter < Props > (({ router }: Props) => ())
```

**Comment by KidkArolis** [comment]
I tried ignoring the line, but that doesn't seem to work:

```
// prettier-ignore
export default withRouter<Props>(Index)
```

**Comment by KidkArolis** [comment]
Same issue filed in the prettier repo: https://github.com/prettier/prettier/issues/5460

**Comment by KidkArolis** [comment]
// prettier-ignore works if I create `.eslintrc` with:

```
{
  "extends": ["plugin:flowtype/recommended"],
  "plugins": ["flowtype"],
}
```

**Comment by KidkArolis** [comment]
Kinda works now after .. updating all dependencies. I think it might be ok after all. Will come back after I double check.

**Comment by sheerun** [comment]
prettier-standard 9 uses most recent version of prettier so it should fix the issue (you can configure parser by create appropriate .prettierrc file, .eslintrc is now ignored)
