### ISSUE TITLE
Ignore .editorconfig

### ISSUE THREAD

**Issue by Windvis** [sheerun/prettier-standard#79]
It seems like prettier-standard (or the Prettier side) uses the .editorconfig file if present. This makes it possible for a project to set the indent size to 4 spaces, which is not following the `standard` convention. It doesn't seem to trigger any linting errors either.

Is it somehow possible to ignore .editorconfig? We use prettier-standard in our company since it is easy to enforce and we don't want anyone to mess with linting / formatting rules. But is seems they still can though.. 😄

**Comment by sheerun** [comment]
There's no way to ignore editorconfig. If you don't want 4 spaces indentation then don't put such setting in this file

**Comment by sheerun** [comment]
I guess explicitly setting indentation to 2 spaces in  .prettierrc should also help

**Comment by Windvis** [comment]
Yea, it's more about preventing other teams in our company to mess with these kind of things. There are some "stubborn" people who _NEED_ their semicolons, etc 😄.

Anyway, it looks like prettier and prettierx have a `--no-editorconfig` cli option. If I run prettierx with the same options that prettier-standard passes to it and also add the `--no-editorconfig` option, everything is ok.

Maybe this can be added by default?

**Comment by sheerun** [comment]
You mean .editorconfig in user's home directory?
