### ISSUE TITLE
Recommended way of VS Code integration

### ISSUE THREAD

**Issue by pReya** [sheerun/prettier-standard#87]
Hey there, I'd love to know about the recommended way to integrate with VS Code. It's a pretty popular editor these days, so it might be a good idea to add it to the readme. I'd love to help with this when I've found the best solution. Currently I'm using it with a "Run on Save" plugin (https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave). Are there other/better ways?

**Comment by sheerun** [comment]
You can use it but personally I would not bother and use for example https://github.com/sheerun/modern-node that auto-formats files when commit is made

**Comment by mesqueeb** [comment]
@pReya I use this extension for VSCode:
https://github.com/numso/prettier-standard-vscode
