### ISSUE TITLE
Wrong formatting of generic function

### ISSUE THREAD

**Issue by havenchyk** [sheerun/prettier-standard#89]
Hey, I have a code snippet that is correctly formatted with `prettierx` (even 0.7.1), but is not correctly formatted with `prettier-standard`

```
const foo = function<T>(bar: T) {
  return bar
}
```

here after prettier-standard formatting, a space between `<T>` and `(bar: T)` will be added.

Initially I created [an issue against prettierx](https://github.com/brodybits/prettierx/issues/52#issuecomment-557823798)

adding a flag into `.prettierrc.js` didn't affect output.

**Comment by brodybits** [comment]
> Initially I created [an issue against prettierx](https://github.com/brodybits/prettierx/issues/52#issuecomment-557823798)

brodybits/prettierx#52 and this looks like something that should be resolved on prettierx

A new test case in prettierx would be very helpful.

**Comment by havenchyk** [comment]
Seems this weird behavior is fixed in prettierx, but to me it's not clear how to bump version of prettierx after it dropped typescript from dependencies. @brodybits what's your thoughts on it?

**Comment by havenchyk** [comment]
@sheerun could you please publish package once again?

**Comment by sheerun** [comment]
done
