### ISSUE TITLE
Computed property even spacing standard

### ISSUE THREAD

**Issue by celso-henrique** [sheerun/prettier-standard#9]
Expected "[" and "]" to be on the same line (standard/computed-property-even-spacing)

Ex:
attendancesByStudentId[studentId] = attendancesByStudentId[studentId] || [];

Prettier standard will turn it into:
attendancesByStudentId[studentId] = attendancesByStudentId[
  studentId
] || [];

In this case maybe it should be on the same line.

**Comment by sheerun** [comment]
Could you post this issue on https://github.com/prettier/prettier ?

**Comment by celso-henrique** [comment]
okay 👍

**Comment by gutosanches** [comment]
The issue is about prettier-standard though, isn't it? It is a standard rule being broken after all (standard/computed-property-even-spacing).
