### ISSUE TITLE
Wrong formatting of the trick for generics in tsx

### ISSUE THREAD

**Issue by havenchyk** [sheerun/prettier-standard#94]
I'm not sure should it be solved here on at prettierx.

`<T,>(props: Props<T>) => {}` will be fomatted without a space: `<T,>`, but standard adds this space.

Related issue https://github.com/brodybits/prettierx/issues/107

**Comment by sheerun** [comment]
We use prettierx so it needs to be fixed there first

**Comment by havenchyk** [comment]
@sheerun what do you think if we disable rule `comma-spacing` from eslint if it's covered by prettier(x?)

**Comment by sheerun** [comment]
Sorry I’m not fluent with what prettier can do :)

**Comment by sheerun** [comment]
@havenchyk I see what you mean now. I think best option is to send PR to https://github.com/prettier/eslint-config-prettier which we use

**Comment by sheerun** [comment]
Actually it seems it was sent already: https://github.com/prettier/eslint-config-prettier/commit/04c79bf1602c8126da863d0997aef5ff347b73db

**Comment by sheerun** [comment]
I've updated all vendor dependencies and published as 16.2.0, maybe you could check if you have time

**Comment by havenchyk** [comment]
Nice, thanks @sheerun, I'll check it. I migrated my codebase to `T extends unknown`. See [who](https://github.com/typescript-eslint/typescript-eslint/issues/1457) started it 😄?
