### ISSUE TITLE
Where are the release notes?

### ISSUE THREAD

**Issue by kleinfreund** [sheerun/prettier-standard#96]
I can’t seem to find any information about the latest major releases of this package.

Is there a release notes section or a changelog in another location that I missed?

What are the breaking changes in version 15 and 16?

**Comment by sheerun** [comment]
There can be minor breaking changes in formatting and linting as dependencies like prettierx and eslint (and eslint plugins) were updated. Otherwise there are no major changes.

I've added release: https://github.com/sheerun/prettier-standard/releases/tag/v16.2.1
