### ISSUE TITLE
feature: Respect standard's `ignore` rule in package.json

### ISSUE THREAD

**Issue by jasonkarns** [sheerun/prettier-standard#97]
Since it is common (expected? recommended?) to run prettier-standard along with standard, I think it would be a big help if prettier-standard would respect standard's ignore rules from `package.json#standard.ignore`

**Comment by sheerun** [comment]
prettier-standard runs prettier and then eslint with eslint-config-standard. standard is separate CLI that has different configuration options. if you want to ignore some files, please use .prettierignore. if you want to just format some files and not lint others, please use .eslintignore
